export const SET_DASHBOARD_MENU = "SET_DASHBOARD_MENU";
export const SET_MYBOOKING_MENU = "SET_MYBOOKING_MENU";
export const SET_NEWBOOKING_MENU = "SET_NEWBOOKING_MENU";

// sign Up
export const SIGNUP_START = "SIGNUP_START";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAILED = "SIGNUP_FAILED";

// login
export const LOGIN_START = "LOGIN_START";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";

export const AUTHENTICATE_USER = "AUTHENTICATE_USER";
export const LOG_OUT = "LOG_OUT";
